"""Canonical table of the 66 books (Chinese Union Version, simplified).

Each entry: (id, simplified name, standard abbreviation, pinyin syllables,
extra aliases, ibibles.net book code, chapter count).
Shared by build_data.py, fetch_ibibles.py and chajing_cli.py.
"""

BOOKS = [
    (1, "创世记", "创", "chuang shi ji", ["创世纪"], "gen", 50),
    (2, "出埃及记", "出", "chu ai ji ji", [], "exo", 40),
    (3, "利未记", "利", "li wei ji", [], "lev", 27),
    (4, "民数记", "民", "min shu ji", [], "num", 36),
    (5, "申命记", "申", "shen ming ji", [], "deu", 34),
    (6, "约书亚记", "书", "yue shu ya ji", [], "jos", 24),
    (7, "士师记", "士", "shi shi ji", [], "jdg", 21),
    (8, "路得记", "得", "lu de ji", [], "rut", 4),
    (9, "撒母耳记上", "撒上", "sa mu er ji shang", [], "1sa", 31),
    (10, "撒母耳记下", "撒下", "sa mu er ji xia", [], "2sa", 24),
    (11, "列王纪上", "王上", "lie wang ji shang", ["列王记上"], "1ki", 22),
    (12, "列王纪下", "王下", "lie wang ji xia", ["列王记下"], "2ki", 25),
    (13, "历代志上", "代上", "li dai zhi shang", [], "1ch", 29),
    (14, "历代志下", "代下", "li dai zhi xia", [], "2ch", 36),
    (15, "以斯拉记", "拉", "yi si la ji", [], "ezr", 10),
    (16, "尼希米记", "尼", "ni xi mi ji", [], "neh", 13),
    (17, "以斯帖记", "斯", "yi si tie ji", [], "est", 10),
    (18, "约伯记", "伯", "yue bo ji", [], "job", 42),
    (19, "诗篇", "诗", "shi pian", [], "psa", 150),
    (20, "箴言", "箴", "zhen yan", [], "pro", 31),
    (21, "传道书", "传", "chuan dao shu", [], "ecc", 12),
    (22, "雅歌", "歌", "ya ge", [], "son", 8),
    (23, "以赛亚书", "赛", "yi sai ya shu", [], "isa", 66),
    (24, "耶利米书", "耶", "ye li mi shu", [], "jer", 52),
    (25, "耶利米哀歌", "哀", "ye li mi ai ge", [], "lam", 5),
    (26, "以西结书", "结", "yi xi jie shu", [], "eze", 48),
    (27, "但以理书", "但", "dan yi li shu", [], "dan", 12),
    (28, "何西阿书", "何", "he xi a shu", [], "hos", 14),
    (29, "约珥书", "珥", "yue er shu", [], "joe", 3),
    (30, "阿摩司书", "摩", "a mo si shu", [], "amo", 9),
    (31, "俄巴底亚书", "俄", "e ba di ya shu", [], "oba", 1),
    (32, "约拿书", "拿", "yue na shu", [], "jon", 4),
    (33, "弥迦书", "弥", "mi jia shu", [], "mic", 7),
    (34, "那鸿书", "鸿", "na hong shu", [], "nah", 3),
    (35, "哈巴谷书", "哈", "ha ba gu shu", [], "hab", 3),
    (36, "西番雅书", "番", "xi fan ya shu", [], "zep", 3),
    (37, "哈该书", "该", "ha gai shu", [], "hag", 2),
    (38, "撒迦利亚书", "亚", "sa jia li ya shu", [], "zec", 14),
    (39, "玛拉基书", "玛", "ma la ji shu", [], "mal", 4),
    (40, "马太福音", "太", "ma tai fu yin", [], "mat", 28),
    (41, "马可福音", "可", "ma ke fu yin", [], "mar", 16),
    (42, "路加福音", "路", "lu jia fu yin", [], "luk", 24),
    (43, "约翰福音", "约", "yue han fu yin", [], "joh", 21),
    (44, "使徒行传", "徒", "shi tu xing zhuan", [], "act", 28),
    (45, "罗马书", "罗", "luo ma shu", [], "rom", 16),
    (46, "哥林多前书", "林前", "ge lin duo qian shu", [], "1co", 16),
    (47, "哥林多后书", "林后", "ge lin duo hou shu", [], "2co", 13),
    (48, "加拉太书", "加", "jia la tai shu", [], "gal", 6),
    (49, "以弗所书", "弗", "yi fu suo shu", [], "eph", 6),
    (50, "腓立比书", "腓", "fei li bi shu", ["腓利比书"], "phi", 4),
    (51, "歌罗西书", "西", "ge luo xi shu", [], "col", 4),
    (52, "帖撒罗尼迦前书", "帖前", "tie sa luo ni jia qian shu", [], "1th", 5),
    (53, "帖撒罗尼迦后书", "帖后", "tie sa luo ni jia hou shu", [], "2th", 3),
    (54, "提摩太前书", "提前", "ti mo tai qian shu", [], "1ti", 6),
    (55, "提摩太后书", "提后", "ti mo tai hou shu", [], "2ti", 4),
    (56, "提多书", "多", "ti duo shu", [], "tit", 3),
    (57, "腓利门书", "门", "fei li men shu", [], "phm", 1),
    (58, "希伯来书", "来", "xi bo lai shu", [], "heb", 13),
    (59, "雅各书", "雅", "ya ge shu", [], "jam", 5),
    (60, "彼得前书", "彼前", "bi de qian shu", [], "1pe", 5),
    (61, "彼得后书", "彼后", "bi de hou shu", [], "2pe", 3),
    (62, "约翰一书", "约一", "yue han yi shu", ["约翰壹书", "约壹"], "1jo", 5),
    (63, "约翰二书", "约二", "yue han er shu", ["约翰贰书", "约贰"], "2jo", 1),
    (64, "约翰三书", "约三", "yue han san shu", ["约翰叁书", "约叁", "约参"], "3jo", 1),
    (65, "犹大书", "犹", "you da shu", [], "jud", 1),
    (66, "启示录", "启", "qi shi lu", [], "rev", 22),
]


def book_dicts():
    out = []
    for bid, name, abbr, pinyin, aliases, code, chapters in BOOKS:
        out.append({
            "id": bid,
            "name": name,
            "abbr": abbr,
            "pinyin": pinyin.split(),
            "aliases": aliases,
            "code": code,
            "chapterCount": chapters,
        })
    return out
